package app.models.shoppingCar;

import components.components.mainComponents.swing.scrollbar.ScrollBarCustom;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JScrollPane;


public class ShoppingCarView extends javax.swing.JFrame {
    
    private List<BookViewShCar> books;

    public ShoppingCarView() {
        initComponents();
        init();
        addScroll();
        setBackground(new Color(0, 0, 0 , 0));
        
        books = new ArrayList<>();
    }
    
    
    private void init() {
       headerShoppingCardView.initMoving(this);
       headerShoppingCardView.initEvent(this, panelBackground);
        
    } 
    
    private void addScroll() {
        scroll.setBorder(null);
        scroll.setViewportBorder(null);
        scroll.getViewport().setOpaque(false);
        scroll.setVerticalScrollBar(new ScrollBarCustom());
        scroll.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBackground = new components.mainComponents.swing.PanelBackground();
        headerShoppingCardView = new components.Header();
        userInfoShCarPanel1 = new app.models.shoppingCar.userInfoShCarPanel();
        scroll = new javax.swing.JScrollPane();
        portrait = new components.mainComponents.swing.PanelBackground();
        jLabel8 = new javax.swing.JLabel();
        totalValue = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        userName = new javax.swing.JLabel();
        btnConsultClient = new components.ButtonGradient();
        btnConsultClient1 = new components.ButtonGradient();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        headerShoppingCardView.setOpaque(false);

        portrait.setBackground(new java.awt.Color(221, 221, 221));
        portrait.setLayout(new java.awt.GridLayout(0, 1, 20, 0));
        scroll.setViewportView(portrait);

        jLabel8.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(54, 149, 255));
        jLabel8.setText("Total:");

        totalValue.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        totalValue.setForeground(new java.awt.Color(0, 0, 0));
        totalValue.setText("Total de la compra ");

        jLabel9.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(54, 149, 255));
        jLabel9.setText("Cliente:");

        userName.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        userName.setForeground(new java.awt.Color(0, 0, 0));
        userName.setText("Nombre Cliente");

        btnConsultClient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icon/Book.png"))); // NOI18N
        btnConsultClient.setText("Consultar Cliente");
        btnConsultClient.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 12)); // NOI18N
        btnConsultClient.setGradientColor1(new java.awt.Color(54, 149, 255));
        btnConsultClient.setGradientColor2(new java.awt.Color(54, 149, 255));
        btnConsultClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultClientActionPerformed(evt);
            }
        });

        btnConsultClient1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icon/Book.png"))); // NOI18N
        btnConsultClient1.setText("Confimar ");
        btnConsultClient1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 12)); // NOI18N
        btnConsultClient1.setGradientColor1(new java.awt.Color(54, 149, 255));
        btnConsultClient1.setGradientColor2(new java.awt.Color(54, 149, 255));
        btnConsultClient1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultClient1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBackgroundLayout = new javax.swing.GroupLayout(panelBackground);
        panelBackground.setLayout(panelBackgroundLayout);
        panelBackgroundLayout.setHorizontalGroup(
            panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headerShoppingCardView, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(panelBackgroundLayout.createSequentialGroup()
                .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBackgroundLayout.createSequentialGroup()
                        .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelBackgroundLayout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelBackgroundLayout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(totalValue))
                                    .addGroup(panelBackgroundLayout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(userName))))
                            .addGroup(panelBackgroundLayout.createSequentialGroup()
                                .addGap(85, 85, 85)
                                .addComponent(btnConsultClient1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelBackgroundLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(userInfoShCarPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE))
                    .addGroup(panelBackgroundLayout.createSequentialGroup()
                        .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelBackgroundLayout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(scroll, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelBackgroundLayout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addComponent(btnConsultClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelBackgroundLayout.setVerticalGroup(
            panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBackgroundLayout.createSequentialGroup()
                .addComponent(headerShoppingCardView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userInfoShCarPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(btnConsultClient, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scroll, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(totalValue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(userName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnConsultClient1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setBounds(1600, 130, 300, 845);
    }// </editor-fold>//GEN-END:initComponents

    private void btnConsultClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultClientActionPerformed

        BookViewShCar book = new BookViewShCar("blue-el-campamento-jeans.jpg");
        BookViewShCar book2 = new BookViewShCar("crimes-of-grindelwald.jpg");
        portrait.add(book);
        portrait.add(book2);
        System.out.println("si estoy funcionando");
        
        portrait.updateUI();
    }//GEN-LAST:event_btnConsultClientActionPerformed

    private void btnConsultClient1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultClient1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConsultClient1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShoppingCarView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShoppingCarView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShoppingCarView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShoppingCarView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShoppingCarView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private components.ButtonGradient btnConsultClient;
    private components.ButtonGradient btnConsultClient1;
    private components.Header headerShoppingCardView;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private components.mainComponents.swing.PanelBackground panelBackground;
    private components.mainComponents.swing.PanelBackground portrait;
    private javax.swing.JScrollPane scroll;
    private javax.swing.JLabel totalValue;
    private app.models.shoppingCar.userInfoShCarPanel userInfoShCarPanel1;
    private javax.swing.JLabel userName;
    // End of variables declaration//GEN-END:variables
}
