package app.models.shoppingCar;


public class userInfoShCarPanel extends javax.swing.JPanel {


    public userInfoShCarPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        typeIdSelect = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        userIdNumberInput = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setOpaque(false);

        typeIdSelect.setBackground(new java.awt.Color(255, 255, 255));
        typeIdSelect.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        typeIdSelect.setForeground(new java.awt.Color(204, 204, 204));
        typeIdSelect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "  C.C", "  T.I ", "  C.E " }));
        typeIdSelect.setBorder(null);
        typeIdSelect.setFocusable(false);
        typeIdSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeIdSelectActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 10)); // NOI18N
        jLabel9.setForeground(java.awt.Color.black);
        jLabel9.setText("Documento");

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 10)); // NOI18N
        jLabel7.setForeground(java.awt.Color.black);
        jLabel7.setText("Documento");

        userIdNumberInput.setBackground(new java.awt.Color(255, 255, 255));
        userIdNumberInput.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        userIdNumberInput.setForeground(new java.awt.Color(204, 204, 204));
        userIdNumberInput.setText("Ingrse N° Documento");
        userIdNumberInput.setBorder(null);
        userIdNumberInput.setSelectionColor(new java.awt.Color(30, 30, 30));
        userIdNumberInput.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                userIdNumberInputMousePressed(evt);
            }
        });
        userIdNumberInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userIdNumberInputActionPerformed(evt);
            }
        });

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));

        jLabel10.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 10)); // NOI18N
        jLabel10.setForeground(java.awt.Color.black);
        jLabel10.setText("Tipo de ");

        jLabel8.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 10)); // NOI18N
        jLabel8.setForeground(java.awt.Color.black);
        jLabel8.setText("N° de ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(typeIdSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator3)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userIdNumberInput, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE))
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(typeIdSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userIdNumberInput, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void userIdNumberInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userIdNumberInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userIdNumberInputActionPerformed

    private void userIdNumberInputMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userIdNumberInputMousePressed
        // TODO add your handling code here:
        userIdNumberInput.setText("");
        userIdNumberInput.setForeground(new java.awt.Color(0,0,0));
    }//GEN-LAST:event_userIdNumberInputMousePressed

    private void typeIdSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeIdSelectActionPerformed

    }//GEN-LAST:event_typeIdSelectActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JComboBox<String> typeIdSelect;
    private javax.swing.JTextField userIdNumberInput;
    // End of variables declaration//GEN-END:variables
}
