/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package app.views.steps;

/**
 *
 * @author Cristian Vega
 */
public class Step2 extends javax.swing.JPanel {

    /**
     * Creates new form Step1
     */
    public Step2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cardStep1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        register_nameInput = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        register_typeIdSelect = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        register_userIdNumberInput = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();

        cardStep1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jLabel6.setForeground(java.awt.Color.black);
        jLabel6.setText("Nombre ");

        register_nameInput.setBackground(new java.awt.Color(255, 255, 255));
        register_nameInput.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        register_nameInput.setForeground(new java.awt.Color(204, 204, 204));
        register_nameInput.setText("Ingrese su Nombre ");
        register_nameInput.setBorder(null);
        register_nameInput.setSelectionColor(new java.awt.Color(30, 30, 30));
        register_nameInput.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                register_nameInputMousePressed(evt);
            }
        });
        register_nameInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                register_nameInputActionPerformed(evt);
            }
        });

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Logo.png"))); // NOI18N

        jLabel9.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jLabel9.setForeground(java.awt.Color.black);
        jLabel9.setText("Tipo de Documento");

        register_typeIdSelect.setBackground(new java.awt.Color(255, 255, 255));
        register_typeIdSelect.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        register_typeIdSelect.setForeground(new java.awt.Color(204, 204, 204));
        register_typeIdSelect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cedula ( C.C )", "Tarjeta de Identidad ( T.I )", "Cedula de Extranjeria ( C.E )" }));
        register_typeIdSelect.setBorder(null);
        register_typeIdSelect.setFocusable(false);
        register_typeIdSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                register_typeIdSelectActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jLabel7.setForeground(java.awt.Color.black);
        jLabel7.setText("N° de Documento");

        register_userIdNumberInput.setBackground(new java.awt.Color(255, 255, 255));
        register_userIdNumberInput.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        register_userIdNumberInput.setForeground(new java.awt.Color(204, 204, 204));
        register_userIdNumberInput.setText("Ingrese el numero de su Documento");
        register_userIdNumberInput.setBorder(null);
        register_userIdNumberInput.setSelectionColor(new java.awt.Color(30, 30, 30));
        register_userIdNumberInput.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                register_userIdNumberInputMousePressed(evt);
            }
        });
        register_userIdNumberInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                register_userIdNumberInputActionPerformed(evt);
            }
        });

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout cardStep1Layout = new javax.swing.GroupLayout(cardStep1);
        cardStep1.setLayout(cardStep1Layout);
        cardStep1Layout.setHorizontalGroup(
            cardStep1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardStep1Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(cardStep1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(register_nameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator2)
                    .addComponent(register_typeIdSelect, 0, 262, Short.MAX_VALUE)
                    .addComponent(jSeparator3)
                    .addComponent(register_userIdNumberInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cardStep1Layout.createSequentialGroup()
                .addContainerGap(145, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(121, 121, 121))
        );
        cardStep1Layout.setVerticalGroup(
            cardStep1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardStep1Layout.createSequentialGroup()
                .addComponent(jLabel8)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(register_nameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(register_typeIdSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(register_userIdNumberInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cardStep1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cardStep1, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void register_userIdNumberInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_register_userIdNumberInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_register_userIdNumberInputActionPerformed

    private void register_userIdNumberInputMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_register_userIdNumberInputMousePressed
        // TODO add your handling code here:
        register_userIdNumberInput.setText("");
        register_userIdNumberInput.setForeground(new java.awt.Color(0,0,0));
    }//GEN-LAST:event_register_userIdNumberInputMousePressed

    private void register_typeIdSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_register_typeIdSelectActionPerformed

    }//GEN-LAST:event_register_typeIdSelectActionPerformed

    private void register_nameInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_register_nameInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_register_nameInputActionPerformed

    private void register_nameInputMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_register_nameInputMousePressed
        // TODO add your handling code here:
        register_nameInput.setText("");
        register_nameInput.setForeground(new java.awt.Color(0,0,0));
    }//GEN-LAST:event_register_nameInputMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel cardStep1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField register_nameInput;
    private javax.swing.JComboBox<String> register_typeIdSelect;
    private javax.swing.JTextField register_userIdNumberInput;
    // End of variables declaration//GEN-END:variables
}
