/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package components.register.formSteps;

/**
 *
 * @author Cristian Vega
 */
public class Step1 extends javax.swing.JPanel {

    /**
     * Creates new form Step1
     */
    public Step1() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cardStep1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        login_passwordInput = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        selectCiudad = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        login_userNameInput = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();

        setOpaque(false);

        cardStep1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Logo.png"))); // NOI18N

        login_passwordInput.setBackground(new java.awt.Color(255, 255, 255));
        login_passwordInput.setForeground(new java.awt.Color(204, 204, 204));
        login_passwordInput.setText("jPasswordField1");
        login_passwordInput.setBorder(null);
        login_passwordInput.setSelectionColor(new java.awt.Color(255, 255, 255));
        login_passwordInput.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                login_passwordInputMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                login_passwordInputMousePressed(evt);
            }
        });
        login_passwordInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_passwordInputActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jLabel9.setForeground(java.awt.Color.black);
        jLabel9.setText("Tipo de Usuario");

        selectCiudad.setBackground(new java.awt.Color(255, 255, 255));
        selectCiudad.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        selectCiudad.setForeground(new java.awt.Color(204, 204, 204));
        selectCiudad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lector", "Bibliotecario", "Administrador" }));
        selectCiudad.setBorder(null);
        selectCiudad.setFocusable(false);
        selectCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectCiudadActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jLabel6.setForeground(java.awt.Color.black);
        jLabel6.setText("Usuario ");

        login_userNameInput.setBackground(new java.awt.Color(255, 255, 255));
        login_userNameInput.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        login_userNameInput.setForeground(new java.awt.Color(204, 204, 204));
        login_userNameInput.setText("Ingrese el Nombre de Usuario ");
        login_userNameInput.setBorder(null);
        login_userNameInput.setSelectionColor(new java.awt.Color(30, 30, 30));
        login_userNameInput.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                login_userNameInputMousePressed(evt);
            }
        });
        login_userNameInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_userNameInputActionPerformed(evt);
            }
        });

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jLabel7.setForeground(java.awt.Color.black);
        jLabel7.setText("Contraseña ");

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout cardStep1Layout = new javax.swing.GroupLayout(cardStep1);
        cardStep1.setLayout(cardStep1Layout);
        cardStep1Layout.setHorizontalGroup(
            cardStep1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardStep1Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(cardStep1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(login_userNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator2)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(login_passwordInput, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator3)
                    .addComponent(selectCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(79, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cardStep1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(121, 121, 121))
        );
        cardStep1Layout.setVerticalGroup(
            cardStep1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardStep1Layout.createSequentialGroup()
                .addComponent(jLabel8)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(login_userNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(login_passwordInput, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(selectCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cardStep1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cardStep1, javax.swing.GroupLayout.DEFAULT_SIZE, 428, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void login_passwordInputMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login_passwordInputMouseClicked
        // TODO add your handling code h
    }//GEN-LAST:event_login_passwordInputMouseClicked

    private void login_passwordInputMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login_passwordInputMousePressed
        // TODO add your handling code here:
        login_passwordInput.setText("");
        login_passwordInput.setForeground(new java.awt.Color(0,0,0));
    }//GEN-LAST:event_login_passwordInputMousePressed

    private void login_passwordInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_passwordInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_login_passwordInputActionPerformed

    private void selectCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectCiudadActionPerformed

    }//GEN-LAST:event_selectCiudadActionPerformed

    private void login_userNameInputMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login_userNameInputMousePressed
        // TODO add your handling code here:
        login_userNameInput.setText("");
        login_userNameInput.setForeground(new java.awt.Color(0,0,0));
    }//GEN-LAST:event_login_userNameInputMousePressed

    private void login_userNameInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_userNameInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_login_userNameInputActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel cardStep1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JPasswordField login_passwordInput;
    private javax.swing.JTextField login_userNameInput;
    private javax.swing.JComboBox<String> selectCiudad;
    // End of variables declaration//GEN-END:variables
}
