/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package app.views;

import java.awt.Cursor;
import javax.swing.JLabel;

/**
 *
 * @author SENA
 */
public class Prueba extends javax.swing.JPanel {

    /**
     * Creates new form Prueba
     */
    public Prueba() {
        initComponents();
        jToolBar1.setFloatable(false);
        btnBuy.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }
    
    
//    private JLabel imgJLabel;
    
    public Prueba(String relativeImgPath) {
        initComponents();
        jToolBar1.setFloatable(false);
        btnBuy.setCursor(new Cursor(Cursor.HAND_CURSOR));
//        this.imgJLabel = jLabel;
        
        jLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource(relativeImgPath)));
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        btnSave = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btnBuy = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setOpaque(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/portadas/portadaLibro_0.jpg"))); // NOI18N
        add(jLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        jToolBar1.setBorderPainted(false);
        jToolBar1.setOpaque(false);

        btnSave.setBackground(new java.awt.Color(0, 0, 0));
        btnSave.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 12)); // NOI18N
        btnSave.setForeground(new java.awt.Color(0, 0, 0));
        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Favorites.png"))); // NOI18N
        btnSave.setText("Guardar");
        btnSave.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 15));
        btnSave.setBorderPainted(false);
        btnSave.setContentAreaFilled(false);
        btnSave.setFocusable(false);
        btnSave.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSave.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jToolBar1.add(btnSave);
        jToolBar1.add(jSeparator1);

        btnBuy.setBackground(new java.awt.Color(0, 0, 0));
        btnBuy.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 12)); // NOI18N
        btnBuy.setForeground(new java.awt.Color(0, 0, 0));
        btnBuy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/buy.png"))); // NOI18N
        btnBuy.setText("Comprar");
        btnBuy.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 15));
        btnBuy.setBorderPainted(false);
        btnBuy.setContentAreaFilled(false);
        btnBuy.setFocusable(false);
        btnBuy.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBuy.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnBuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuyActionPerformed(evt);
            }
        });
        jToolBar1.add(btnBuy);

        add(jToolBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, 67));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/portadas/bordeLibro.png"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 160, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        System.out.println("Libro Guardado Exitosamente");
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnBuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuyActionPerformed
        // TODO add your handling code here:
        System.out.println("Libro Comprado Exitosamente");
    }//GEN-LAST:event_btnBuyActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuy;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
